// generated by stringer -type=MessageType; DO NOT EDIT

package firego

import "fmt"

const _MessageType_name = "LogInfoWarnError"

var _MessageType_index = [...]uint8{0, 3, 7, 11, 16}

func (i MessageType) String() string {
	if i < 0 || i+1 >= MessageType(len(_MessageType_index)) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
